Add config for nas

diff --git a/ansible/roles/db_backup/templates/backup_db.sh.j2 b/ansible/roles/db_backup/templates/backup_db.sh.j2
--- a/ansible/roles/db_backup/templates/backup_db.sh.j2
+++ b/ansible/roles/db_backup/templates/backup_db.sh.j2
@@ -28,8 +28,16 @@ docker exec "${DB_CONTAINER}" mariadb-dump -u"${DB_USER}" -p"${DB_PASS}" "${DB_N
 # Rotation locale
 find "${BACKUP_DIR}" -type f -name "${SITE}_*.sql.gz" -mtime +{{ db_backup_retention_days }} -delete
 
-# Rsync vers NAS
-{% if db_backup_rsync_enabled %}
-RSYNC_SSH="ssh -i {{ db_backup_nas_ssh_key }} -o StrictHostKeyChecking=accept-new"
-rsync -az --chmod=F600 --rsh="${RSYNC_SSH}" "${OUT}" "{{ db_backup_nas_user }}@{{ db_backup_nas_host }}:{{ db_backup_nas_dir }}/"
+# Copie vers NAS via NFS (si activé)
+{% if db_backup_nfs_enabled and db_backup_copy_to_nas %}
+NAS_DIR="{{ db_backup_nfs_mountpoint }}"
+
+# Vérifie que c'est bien monté (sinon on échoue)
+if ! mountpoint -q "${NAS_DIR}"; then
+  echo "ERROR: NFS mount not present: ${NAS_DIR}" >&2
+  exit 1
+fi
+
+# Copie du fichier dump vers le NAS
+install -m 600 "${OUT}" "${NAS_DIR}/"
 {% endif %}
